version: '3.8'

services:
  localstack:
    image: localstack/localstack
    ports:
      - "4566-4599:4566-4599"
    environment:
      SERVICES: s3
      DEBUG: "1"
    volumes:
      - ./awslocal:/docker-entrypoint-initaws.d:ro

  caddy:
    build: .
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
    ports:
      - "80:80"
    environment:
      AWS_ACCESS_KEY_ID: dummy
      AWS_SECRET_ACCESS_KEY: dummy
      ENDPOINT: http://localstack:4566/
    command: ["caddy", "run", "--config", "/etc/caddy/Caddyfile", "--adapter", "caddyfile", "--watch"]
